In [10]:
import pandas as pd
from pandas import Series,DataFrame

In [51]:
student=DataFrame([[60,80,70],[50,75,85],[90,80,85]],
                 index=["홍길동","박찬호","손흥민"],
                 columns=["영어","수학","국어"])
student

영어  수학  국어
홍길동  60  80  70
박찬호  50  75  85
손흥민  90  80  85

In [6]:
# 제임스 row,data 추가
student = student.set_value('제임스','영어',100)
student = student.set_value('제임스','수학',50)
student = student.set_value('제임스','국어',80)
student

C:\Users\yu\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  
C:\Users\yu\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\yu\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  after removing the cwd from sys.path.


영어    수학    국어
홍길동   60.0  80.0  70.0
박찬호   50.0  75.0  85.0
손흥민   90.0  80.0  85.0
제임스  100.0  50.0  80.0

In [18]:
# at,iat 인덱서는 loc,iloc 인덱서 보다 속도가 빠름, 한개의 스칼라 값만을 찾는다
student.at['제임스',['영어':] = [100,50,80]


SyntaxError: invalid syntax (<ipython-input-18-66a9394f7488>, line 2)

In [52]:
student.at['제임스','영어'] = 100
student.at['제임스','수학'] = 50
student.at['제임스','국어'] = 80
student

영어    수학    국어
홍길동   60.0  80.0  70.0
박찬호   50.0  75.0  85.0
손흥민   90.0  80.0  85.0
제임스  100.0  50.0  80.0

In [53]:
# loc 인덱서 사용해서도 가능함 복수의 스칼라를 불러올수 있음
student.loc['제임스',['영어','수학','국어']] = [100,50,80]
student

영어    수학    국어
홍길동   60.0  80.0  70.0
박찬호   50.0  75.0  85.0
손흥민   90.0  80.0  85.0
제임스  100.0  50.0  80.0

In [54]:
student.at['제임스','영어'] = 90
student

영어    수학    국어
홍길동  60.0  80.0  70.0
박찬호  50.0  75.0  85.0
손흥민  90.0  80.0  85.0
제임스  90.0  50.0  80.0

In [64]:
#새데이터프레임을 기존 데이터 프레임과 합침
student_new = DataFrame([[60,80,70],[50,75,85],[90,80,85]],
                       index = ['유수원','한라온','한서호'],
                       columns = ['영어','수학','국어'])
student_new

TypeError: int() argument must be a string, a bytes-like object or a number, not 'DataFrame'

In [56]:
student = student.append(student_new)
student

영어    수학    국어
홍길동  60.0  80.0  70.0
박찬호  50.0  75.0  85.0
손흥민  90.0  80.0  85.0
제임스  90.0  50.0  80.0
유수원  60.0  80.0  70.0
한라온  50.0  75.0  85.0
한서호  90.0  80.0  85.0

In [57]:
## concat 사용해서 합치기
student1=DataFrame([[60,80,70],[50,75,85],[90,80,85]],
                  index=['싸이','나얼','윤상'],
                  columns=['영어','수학','국어'])
student1

영어  수학  국어
싸이  60  80  70
나얼  50  75  85
윤상  90  80  85

In [58]:
student = pd.concat([student,student1])
student

영어    수학    국어
홍길동  60.0  80.0  70.0
박찬호  50.0  75.0  85.0
손흥민  90.0  80.0  85.0
제임스  90.0  50.0  80.0
유수원  60.0  80.0  70.0
한라온  50.0  75.0  85.0
한서호  90.0  80.0  85.0
싸이   60.0  80.0  70.0
나얼   50.0  75.0  85.0
윤상   90.0  80.0  85.0

In [ ]:
# '과학' 컬럼추가하기
#학생수만큼 점수입력 숫자 안맞으면 에러


In [59]:
student['과학']=[100,80,86,90,95,90,80,90,80,95]
student

영어    수학    국어   과학
홍길동  60.0  80.0  70.0  100
박찬호  50.0  75.0  85.0   80
손흥민  90.0  80.0  85.0   86
제임스  90.0  50.0  80.0   90
유수원  60.0  80.0  70.0   95
한라온  50.0  75.0  85.0   90
한서호  90.0  80.0  85.0   80
싸이   60.0  80.0  70.0   90
나얼   50.0  75.0  85.0   80
윤상   90.0  80.0  85.0   95

In [67]:
student['한국사'] = '조선'   #조선이 복사되서 값으로 들어감
student

영어    수학    국어   과학 한국사
홍길동  60.0  80.0  70.0  100  조선
박찬호  50.0  75.0  85.0   80  조선
손흥민  90.0  80.0  85.0   86  조선
제임스  90.0  50.0  80.0   90  조선
유수원  60.0  80.0  70.0   95  조선
한라온  50.0  75.0  85.0   90  조선
한서호  90.0  80.0  85.0   80  조선
싸이   60.0  80.0  70.0   90  조선
나얼   50.0  75.0  85.0   80  조선
윤상   90.0  80.0  85.0   95  조선

In [68]:
#'한국사'컬럼 삭제
del student['한국사']
student

영어    수학    국어   과학
홍길동  60.0  80.0  70.0  100
박찬호  50.0  75.0  85.0   80
손흥민  90.0  80.0  85.0   86
제임스  90.0  50.0  80.0   90
유수원  60.0  80.0  70.0   95
한라온  50.0  75.0  85.0   90
한서호  90.0  80.0  85.0   80
싸이   60.0  80.0  70.0   90
나얼   50.0  75.0  85.0   80
윤상   90.0  80.0  85.0   95

In [69]:
# '제임스' 행 삭제
# student.drop('제임스') ##변수에 컬럼지운 수정본을 넣어주면 적용
student = student.drop('제임스',axis = 0)
student

영어    수학    국어   과학
홍길동  60.0  80.0  70.0  100
박찬호  50.0  75.0  85.0   80
손흥민  90.0  80.0  85.0   86
유수원  60.0  80.0  70.0   95
한라온  50.0  75.0  85.0   90
한서호  90.0  80.0  85.0   80
싸이   60.0  80.0  70.0   90
나얼   50.0  75.0  85.0   80
윤상   90.0  80.0  85.0   95

In [70]:
student['영어']

홍길동    60.0
박찬호    50.0
손흥민    90.0
유수원    60.0
한라온    50.0
한서호    90.0
싸이     60.0
나얼     50.0
윤상     90.0
Name: 영어, dtype: float64

In [71]:
student[['영어','국어']]

영어    국어
홍길동  60.0  70.0
박찬호  50.0  85.0
손흥민  90.0  85.0
유수원  60.0  70.0
한라온  50.0  85.0
한서호  90.0  85.0
싸이   60.0  70.0
나얼   50.0  85.0
윤상   90.0  85.0

In [72]:
student.loc['나얼',['영어','국어']]

영어    50.0
국어    85.0
Name: 나얼, dtype: float64

In [74]:
student.loc[['나얼','윤상'],['영어','국어']]

영어    국어
나얼  50.0  85.0
윤상  90.0  85.0

In [75]:
student.iloc[[3,7],[0,2]]

영어    국어
유수원  60.0  70.0
나얼   50.0  85.0

In [76]:
# 비슷한 인덱싱 방법들
student[student.index.isin(['나얼','윤상'])]

영어    수학    국어  과학
나얼  50.0  75.0  85.0  80
윤상  90.0  80.0  85.0  95

In [77]:
#&,| 연산자를 사용한 조건부검색

student[student['수학']>90]

Empty DataFrame
Columns: [영어, 수학, 국어, 과학]
Index: []

In [80]:
student[(student['수학']>90)&(student['과학']>80)]

Empty DataFrame
Columns: [영어, 수학, 국어, 과학]
Index: []

In [81]:
student[(student['수학']>90)|(student['과학']>80)]

영어    수학    국어   과학
홍길동  60.0  80.0  70.0  100
손흥민  90.0  80.0  85.0   86
유수원  60.0  80.0  70.0   95
한라온  50.0  75.0  85.0   90
싸이   60.0  80.0  70.0   90
윤상   90.0  80.0  85.0   95

In [83]:
student.loc[student['수학']>90]

Empty DataFrame
Columns: [영어, 수학, 국어, 과학]
Index: []

In [84]:
student.loc[student['국어']==85]

영어    수학    국어  과학
박찬호  50.0  75.0  85.0  80
손흥민  90.0  80.0  85.0  86
한라온  50.0  75.0  85.0  90
한서호  90.0  80.0  85.0  80
나얼   50.0  75.0  85.0  80
윤상   90.0  80.0  85.0  95

In [87]:
#.isin() 함수로 수학에 85,95점이 있는지 확인

student['수학'].isin([75,95])

#boolen 형식으로 ture flase값이 나옴

홍길동    False
박찬호     True
손흥민    False
유수원    False
한라온     True
한서호    False
싸이     False
나얼      True
윤상     False
Name: 수학, dtype: bool

In [88]:
#위에 boolen형식 값을 기반으로 수학이 85,95인 값들을 뽑아냄
student.loc[student['수학'].isin([75,95])]

영어    수학    국어  과학
박찬호  50.0  75.0  85.0  80
한라온  50.0  75.0  85.0  90
나얼   50.0  75.0  85.0  80

In [ ]:
# xs 인덱서 사용

In [89]:
student.xs('윤상')

영어    90.0
수학    80.0
국어    85.0
과학    95.0
Name: 윤상, dtype: float64

In [96]:
student.xs('영어',axis=1)

홍길동    60.0
박찬호    50.0
손흥민    90.0
유수원    60.0
한라온    50.0
한서호    90.0
싸이     60.0
나얼     50.0
윤상     90.0
Name: 영어, dtype: float64

In [94]:
student['영어']

홍길동    60.0
박찬호    50.0
손흥민    90.0
유수원    60.0
한라온    50.0
한서호    90.0
싸이     60.0
나얼     50.0
윤상     90.0
Name: 영어, dtype: float64

In [98]:
#인덱스 이름바꾸기 

student.rename(index={'윤상':'김상'})
student
#역시 적용안됨 변수호출해서 넣어줘야됨

영어    수학    국어   과학
홍길동  60.0  80.0  70.0  100
박찬호  50.0  75.0  85.0   80
손흥민  90.0  80.0  85.0   86
유수원  60.0  80.0  70.0   95
한라온  50.0  75.0  85.0   90
한서호  90.0  80.0  85.0   80
싸이   60.0  80.0  70.0   90
나얼   50.0  75.0  85.0   80
윤상   90.0  80.0  85.0   95

In [100]:
student = student.rename(index={'윤상':'김상'})
student

영어    수학    국어   과학
홍길동  60.0  80.0  70.0  100
박찬호  50.0  75.0  85.0   80
손흥민  90.0  80.0  85.0   86
유수원  60.0  80.0  70.0   95
한라온  50.0  75.0  85.0   90
한서호  90.0  80.0  85.0   80
싸이   60.0  80.0  70.0   90
나얼   50.0  75.0  85.0   80
김상   90.0  80.0  85.0   95

In [101]:
# column 이름바꾸기 

student = student.rename(columns={'과학':'물리'})
student

영어    수학    국어   물리
홍길동  60.0  80.0  70.0  100
박찬호  50.0  75.0  85.0   80
손흥민  90.0  80.0  85.0   86
유수원  60.0  80.0  70.0   95
한라온  50.0  75.0  85.0   90
한서호  90.0  80.0  85.0   80
싸이   60.0  80.0  70.0   90
나얼   50.0  75.0  85.0   80
김상   90.0  80.0  85.0   95

In [ ]:
[문제112] 아래와 같은 모양의 표를 생성하세요. 

      PYTHON   R  SQL
2014      60  90   50
2015      80  65   75
2016      70  75   85

In [157]:
import pandas as pd
from pandas import Series,DataFrame

lans = DataFrame([[60,90,50],[80,65,75],[70,75,85]],
                index=[str(i) for i in range(2014,2017)],
                columns=['PYTHON','R','SQL'])
lans

PYTHON   R  SQL
2014      60  90   50
2015      80  65   75
2016      70  75   85

In [ ]:
[문제113] 'PYTHON' 열을 선택하세요.

In [158]:
lans['PYTHON']

2014    60
2015    80
2016    70
Name: PYTHON, dtype: int64

In [ ]:
[문제114] '2014' 행 정보를 출력하세요.

In [159]:
lans.loc['2014']

PYTHON    60
R         90
SQL       50
Name: 2014, dtype: int64

In [ ]:
[문제115] 인덱스번호를 기준으로 1부터 2번까지 출력하세요.

In [115]:
lans.iloc[1:3]

PYTHON   R  SQL
2015      80  65   75
2016      70  75   85

In [ ]:
[문제116] PYTHON의 값을 기준으로 60보다 큰값을 가지고 있는 행 정보를 출력하세요.

In [118]:
lans[lans['PYTHON']>60]

PYTHON   R  SQL
2015      80  65   75
2016      70  75   85

In [ ]:
[문제117] PYTHON의 값을 기준으로 60 보다 큰값을 가지고 있는 PYTHON 정보만 출력하세요.

In [123]:
lans['PYTHON'][lans['PYTHON']>60]

2015    80
2016    70
Name: PYTHON, dtype: int64

In [124]:
lans.loc[lans['PYTHON']>60,'PYTHON']

2015    80
2016    70
Name: PYTHON, dtype: int64

In [ ]:
[문제118] '2015' 행값 중에 PYTHON 정보만 출력하세요

In [125]:
lans.loc['2015','PYTHON']

80

In [ ]:
[문제119] '2015'  행값 중에 PYTHON, R 정보 출력하세요 

In [126]:
lans.loc['2015',['PYTHON','R']]

PYTHON    80
R         65
Name: 2015, dtype: int64

In [ ]:
[문제120] 'R' 열 정보를 출력하세요.

In [127]:
lans['R']

2014    90
2015    65
2016    75
Name: R, dtype: int64

In [128]:
lans.loc[:,'R']

2014    90
2015    65
2016    75
Name: R, dtype: int64

In [ ]:
[문제121] 2013 행을 추가하세요. PYTHON : 70,  SQL : 90, R : 85

In [160]:
lans.loc['2013'] = [70,90,85]
lans

PYTHON   R  SQL
2014      60  90   50
2015      80  65   75
2016      70  75   85
2013      70  90   85

In [ ]:
#선생님 풀이
frame.at['2013','PYTHON']=70
frame.at['2013','PYTHON']=90
frame.at['2013','PYTHON']=85
frame

In [ ]:
[문제122] PLSQL 열을 추가한 후 값은 0로 설정하세요

In [161]:
lans['PLSQL'] = 0
lans

PYTHON   R  SQL  PLSQL
2014      60  90   50      0
2015      80  65   75      0
2016      70  75   85      0
2013      70  90   85      0

In [136]:
#선생님 풀이
lans['PLSQL']=[str(i) for i in '0'*4]
lans

PYTHON   R  SQL PLSQL
2014      60  90   50     0
2015      80  65   75     0
2016      70  75   85     0
2013      70  90   85     0

In [137]:
# reindex 사용해서 행정리
lans.reindex([str(i) for i in range(2013,2017)])

PYTHON   R  SQL PLSQL
2013      70  90   85     0
2014      60  90   50     0
2015      80  65   75     0
2016      70  75   85     0

In [ ]:
[문제123] PLSQL 열의 값은 2013 : 50, 2014 : 60, 2015 : 80, 2016 : 90 으로 수정하세요.

In [140]:
lans = lans.reindex([str(i) for i in range(2013,2017)])
lans['PLSQL'] = [50,60,80,90]
lans

PYTHON   R  SQL  PLSQL
2013      70  90   85     50
2014      60  90   50     60
2015      80  65   75     80
2016      70  75   85     90

In [164]:
lans = lans.reindex([str(i) for i in range(2013,2017)])
x = [str(i) for i in range(2013,2017)]
lans.loc[x,'PLSQL'] = [50,60,80,90]

In [165]:
lans

PYTHON   R  SQL  PLSQL
2013      70  90   85     50
2014      60  90   50     60
2015      80  65   75     80
2016      70  75   85     90

In [ ]:
[문제124] 2016년도에 있는 정보 출력하세요

In [143]:
lans.loc['2016',:]

PYTHON    70
R         75
SQL       85
PLSQL     90
Name: 2016, dtype: int64

In [ ]:
[문제125] 2015, 2016년도에  정보 출력하세요.

In [166]:
lans.loc[['2015','2016'],:]

PYTHON   R  SQL  PLSQL
2015      80  65   75     80
2016      70  75   85     90

In [ ]:
[문제126] 2016년도에 PYTHON 정보만 출력하세요.

In [168]:
lans.at['2016','PYTHON']

70

In [ ]:
[문제127] 2016년도에 PYTHON, SQL 정보 출력하세요

In [169]:
lans.loc['2016',['PYTHON','SQL']]

PYTHON    70
SQL       85
Name: 2016, dtype: int64

In [ ]:
[문제128] SQL 점수가 80점보다 이상인 정보를 출력하세요.

In [170]:
lans[lans['SQL']>80]

PYTHON   R  SQL  PLSQL
2013      70  90   85     50
2016      70  75   85     90

In [ ]:
[문제129]PYTHON 점수가 80 이상 또는 SQL 점수가 90 이상인 데이터 출력하세요.

In [174]:
lans[(lans['PYTHON']>=80) | (lans['SQL'] >= 90)]

PYTHON   R  SQL  PLSQL
2015      80  65   75     80

In [ ]:
[문제130] PYTHON 점수가 80 이상 이고 SQL 점수 90 이상인 데이터 출력하세요.

In [175]:
lans[(lans['PYTHON']>=80) & (lans['SQL']>=90)]

Empty DataFrame
Columns: [PYTHON, R, SQL, PLSQL]
Index: []

In [ ]:
[문제131] SQL 점수가 80점 미만인 SQL정보 출력하세요

In [177]:
lans[lans['SQL']<80]['SQL']

2014    50
2015    75
Name: SQL, dtype: int64

In [178]:
lans.loc[lans['SQL']<80,'SQL']

2014    50
2015    75
Name: SQL, dtype: int64

In [179]:
import pandas as pd
from pandas import Series,DataFrame

obj1=Series([10,5,3,7],index=['a','b','c','d'])
obj2=Series([2,4,6,8,10],index=['a','b','c','d','f'])

In [180]:
#시리즈+시리즈 : 인덱스 이름을 이용해 join 하듯이 연산작용함
# f는 NaN이 나옴
obj1+obj2

a    12.0
b     9.0
c     9.0
d    15.0
f     NaN
dtype: float64

In [182]:
obj1

a    10
b     5
c     3
d     7
dtype: int64

In [184]:
#add 함수 사용
obj1.add(obj2,fill_value=0)

a    12.0
b     9.0
c     9.0
d    15.0
f    10.0
dtype: float64

In [185]:
#빼기
obj1-obj2

a    8.0
b    1.0
c   -3.0
d   -1.0
f    NaN
dtype: float64

In [186]:
#sub 함수 사용
obj1.sub(obj2,fill_value=0)

a     8.0
b     1.0
c    -3.0
d    -1.0
f   -10.0
dtype: float64

In [187]:
#곱하기
obj1*obj2

a    20.0
b    20.0
c    18.0
d    56.0
f     NaN
dtype: float64

In [188]:
# mul 함수 사용
obj1.mul(obj2,fill_value=1)

a    20.0
b    20.0
c    18.0
d    56.0
f    10.0
dtype: float64

In [189]:
#나누기
obj1/obj2

a    5.000
b    1.250
c    0.500
d    0.875
f      NaN
dtype: float64

In [190]:
# div 함수 사용
obj1.div(obj2,fill_value=1)

a    5.000
b    1.250
c    0.500
d    0.875
f    0.100
dtype: float64

In [191]:
obj1*10

a    100
b     50
c     30
d     70
dtype: int64

In [192]:
import numpy as np

In [193]:
df1=DataFrame(np.arange(6).reshape(2,3),
             index=['2015','2016'],
             columns=['python','sql','plsql'])

In [196]:
df2=DataFrame(np.arange(12).reshape(3,4),
             index=['2014','2015','2016'],
             columns=['python','r','sql','plsql'])

In [197]:
#인덱스와 컬럼을 기준으로 연산작용하며 길이가 맞지않으면 NaN으로 입력된다.
df1+df2

plsql  python   r   sql
2014    NaN     NaN NaN   NaN
2015    9.0     4.0 NaN   7.0
2016   16.0    11.0 NaN  14.0

In [198]:
df1.add(df2,fill_value=0)

plsql  python    r   sql
2014    3.0     0.0  1.0   2.0
2015    9.0     4.0  5.0   7.0
2016   16.0    11.0  9.0  14.0

In [199]:
df1.sub(df2,fill_value=0)

plsql  python    r  sql
2014   -3.0     0.0 -1.0 -2.0
2015   -5.0    -4.0 -5.0 -5.0
2016   -6.0    -5.0 -9.0 -6.0

In [200]:
df1.mul(df2,fill_value=1)

plsql  python    r   sql
2014    3.0     0.0  1.0   2.0
2015   14.0     0.0  5.0   6.0
2016   55.0    24.0  9.0  40.0

In [201]:
#inf : infinity 무한대
df1.div(df2,fill_value=1)

plsql  python         r       sql
2014  0.333333     inf  1.000000  0.500000
2015  0.285714   0.000  0.200000  0.166667
2016  0.454545   0.375  0.111111  0.400000

In [203]:
obj=np.arange(15).reshape(5,3)
obj

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [204]:
#0번행 뽑기
obj[0]

array([0, 1, 2])

In [205]:
obj1 = obj[0]
obj1

array([0, 1, 2])

In [ ]:
#행렬 연산에서는 행렬수가 맞아야 연산외되지만... 연산이됨
#broadcasting(브로드캐스팅)기능이 돌아가 연산이됨

In [206]:
obj+obj1

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13],
       [12, 14, 16]])

In [ ]:
            ||   broadcasting

obj                  obj1
0,1,2       +        0,1,2
3,4,5                0,1,2
6,7,8                0,1,2
9,10,11              0,1,2
12,13,14             0,1,2


In [207]:
obj1.repeat(5)

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2])

In [208]:
obj1.repeat(5).reshape(3,5)

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2]])

In [209]:
obj1.repeat(5).reshape(3,5).T

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [210]:
obj - obj1.repeat(5).reshape(3,5).T

array([[ 0,  0,  0],
       [ 3,  3,  3],
       [ 6,  6,  6],
       [ 9,  9,  9],
       [12, 12, 12]])

In [213]:
df1 = DataFrame(np.arange(15).reshape(5,3),
               index = [str(i) for i in range(2012,2017)],
               columns = ['서울','부산','광주'])
df1

서울  부산  광주
2012   0   1   2
2013   3   4   5
2014   6   7   8
2015   9  10  11
2016  12  13  14

In [215]:
s = df1.iloc[0]
s

서울    0
부산    1
광주    2
Name: 2012, dtype: int32

In [ ]:
#  Series + DataFrame :  
    #시리즈의 인덱스와 데이터프레임의 컬럼명이 같으면 더해짐 
    #컬럼이름,인덱스명을 기준으로 더해짐

In [216]:
type(s)

pandas.core.series.Series

In [217]:
df1 + s

서울  부산  광주
2012   0   2   4
2013   3   5   7
2014   6   8  10
2015   9  11  13
2016  12  14  16

In [ ]:
#열수가 다를때의 series+DataFrame

In [219]:
s2 = Series([1,2,3,4], index=['서울','부산','광주','제주'])
s2

서울    1
부산    2
광주    3
제주    4
dtype: int64

In [220]:
df1 + s2

광주  부산  서울  제주
2012   5   3   1 NaN
2013   8   6   4 NaN
2014  11   9   7 NaN
2015  14  12  10 NaN
2016  17  15  13 NaN

In [223]:
df1 = DataFrame(np.arange(15).reshape(5,3),
               index=[str(i) for i in range(2012,2017)],
               columns=['서울','부산','광주'])
df1

서울  부산  광주
2012   0   1   2
2013   3   4   5
2014   6   7   8
2015   9  10  11
2016  12  13  14

In [224]:
s3=Series([0,3,6,9,12],index=[str(i) for i in range(2012,2017)])
s3

2012     0
2013     3
2014     6
2015     9
2016    12
dtype: int64

In [225]:
df1 + s3 #이상하게 더해짐
# 시리즈의 인덱스가 데이터프레임의 컬럼명과 다르다
#브로드캐스팅 이용할때는 축을 생각하자...
    #열단위로 3개가 만들어져야됨   
    #단. 인덱스가 일치해야된다.

2012  2013  2014  2015  2016  광주  부산  서울
2012   NaN   NaN   NaN   NaN   NaN NaN NaN NaN
2013   NaN   NaN   NaN   NaN   NaN NaN NaN NaN
2014   NaN   NaN   NaN   NaN   NaN NaN NaN NaN
2015   NaN   NaN   NaN   NaN   NaN NaN NaN NaN
2016   NaN   NaN   NaN   NaN   NaN NaN NaN NaN

In [226]:
df1.add(s3,axis=0) # 행을 기준으로 더하게 ( axis=0 ) 지정해서 잘 더해진다. 

서울  부산  광주
2012   0   1   2
2013   6   7   8
2014  12  13  14
2015  18  19  20
2016  24  25  26

In [227]:
import pandas as pd
from pandas import Series,DataFrame

pro=DataFrame([[60,90,50],[80,65,75],[70,75,85]],
              index=[str(i) for i in range(2014,2017)],
              columns=['PYTHON','R','SQL'])
pro

PYTHON   R  SQL
2014      60  90   50
2015      80  65   75
2016      70  75   85

In [230]:
pro.loc['2014']

PYTHON    60
R         90
SQL       50
Name: 2014, dtype: int64

In [231]:
pro[1:3]

PYTHON   R  SQL
2015      80  65   75
2016      70  75   85

In [233]:
pro[pro['PYTHON']>60]

PYTHON   R  SQL
2015      80  65   75
2016      70  75   85

In [234]:
pro[pro['PYTHON']>60]['PYTHON']

2015    80
2016    70
Name: PYTHON, dtype: int64

In [235]:
pro.loc['2015','PYTHON']

80

In [236]:
pro.loc['2015']['PYTHON']

80

In [237]:
pro.loc['2015'][['PYTHON','R']]

PYTHON    80
R         65
Name: 2015, dtype: int64

In [238]:
pro.loc['2015',['PYTHON','R']]

PYTHON    80
R         65
Name: 2015, dtype: int64

In [239]:
s1 = Series([70,90,85],index=['PYTHON','R','SQL'])
s1

PYTHON    70
R         90
SQL       85
dtype: int64

In [240]:
pro.loc['2013']=[70,90,85]
pro

PYTHON   R  SQL
2014      60  90   50
2015      80  65   75
2016      70  75   85
2013      70  90   85

In [241]:
pro['PLSQL']=[str(i) for i in '0'*4]
pro

PYTHON   R  SQL PLSQL
2014      60  90   50     0
2015      80  65   75     0
2016      70  75   85     0
2013      70  90   85     0

In [244]:
pro.reindex([str(i) for i in range(2013,2017)])

PYTHON   R  SQL PLSQL
2013      70  90   85     0
2014      60  90   50     0
2015      80  65   75     0
2016      70  75   85     0

In [246]:
pro['PLSQL']=[50,60,80,90]
pro

PYTHON   R  SQL  PLSQL
2014      60  90   50     50
2015      80  65   75     60
2016      70  75   85     80
2013      70  90   85     90

In [247]:
pro.loc[['2015','2016']]

PYTHON   R  SQL  PLSQL
2015      80  65   75     60
2016      70  75   85     80

In [250]:
pro.loc['2016','PYTHON']

70

In [251]:
pro.loc['2016',['PYTHON','SQL']]

PYTHON    70
SQL       85
Name: 2016, dtype: int64

In [252]:
pro.loc[pro['PYTHON']>60,'PYTHON']

2015    80
2016    70
2013    70
Name: PYTHON, dtype: int64

In [253]:
pro[pro['PYTHON']>60]['PYTHON']

2015    80
2016    70
2013    70
Name: PYTHON, dtype: int64

In [254]:
pro['PYTHON'][pro['PYTHON']>60]

2015    80
2016    70
2013    70
Name: PYTHON, dtype: int64

In [256]:
pro['SQL'][(pro['SQL']<80) | (pro['PYTHON']>70)]

2014    50
2015    75
Name: SQL, dtype: int64

In [ ]:
#소트 작업

In [ ]:
# Series sort

In [257]:
obj = Series([2,3,5,6],index=['d','c','b','a'])
obj

d    2
c    3
b    5
a    6
dtype: int64

In [ ]:
#인덱스 이름으로 정렬하는방법

In [258]:
obj.sort_index()

a    6
b    5
c    3
d    2
dtype: int64

In [259]:
obj.sort_index(ascending=False)

d    2
c    3
b    5
a    6
dtype: int64

In [ ]:
# 값을 가지고 정렬하는 방법

In [261]:
obj.sort_values()

d    2
c    3
b    5
a    6
dtype: int64

In [262]:
obj.sort_values(ascending=False)

a    6
b    5
c    3
d    2
dtype: int64

In [ ]:
# DataFrame sort

In [260]:
df = DataFrame(np.arange(8).reshape(2,4),
              index=['two','one'],
              columns=['b','d','a','c'])
df

b  d  a  c
two  0  1  2  3
one  4  5  6  7

In [ ]:
#행을 기준으로 소트하기

In [263]:
df.sort_index()

b  d  a  c
one  4  5  6  7
two  0  1  2  3

In [265]:
df.sort_index(ascending=False)

b  d  a  c
two  0  1  2  3
one  4  5  6  7

In [ ]:
#열을기준으로 index 소트하기

In [266]:
df.sort_index(axis=1) #0:row, 1:column

a  b  c  d
two  2  0  3  1
one  6  4  7  5

In [267]:
df.sort_index(axis=1,ascending=False)

d  c  b  a
two  1  3  0  2
one  5  7  4  6

In [ ]:
#  b열을 기준으로해서 행들을  내림차순

In [268]:
df.sort_values(by='b',axis=0, ascending=False)

b  d  a  c
one  4  5  6  7
two  0  1  2  3

In [ ]:
# one 행을 기준으로 해서 열들을 내림차순

In [271]:
df.sort_values(by='one',axis=1,ascending=False)

c  a  d  b
two  3  2  1  0
one  7  6  5  4

In [ ]:
# rank()

In [272]:
obj1=Series([78,88,92,79,67,91,70,86])
obj1

0    78
1    88
2    92
3    79
4    67
5    91
6    70
7    86
dtype: int64

In [273]:
obj1.sort_values()

4    67
6    70
0    78
3    79
7    86
1    88
5    91
2    92
dtype: int64

In [274]:
#작은순으로 랭크표시 
obj1.rank()

0    3.0
1    6.0
2    8.0
3    4.0
4    1.0
5    7.0
6    2.0
7    5.0
dtype: float64

In [ ]:
#큰순으로 랭크표시

In [275]:
obj1.rank(ascending=False)

0    6.0
1    3.0
2    1.0
3    5.0
4    8.0
5    2.0
6    7.0
7    4.0
dtype: float64

In [277]:
# rank가 같은값들을 넣어줌
obj1=Series([78,88,92,79,67,90,70,86,90,90])
obj1

0    78
1    88
2    92
3    79
4    67
5    90
6    70
7    86
8    90
9    90
dtype: int64

In [278]:
obj1.rank()

0     3.0
1     6.0
2    10.0
3     4.0
4     1.0
5     8.0
6     2.0
7     5.0
8     8.0
9     8.0
dtype: float64

In [279]:
obj1.rank(ascending=False)

0     8.0
1     5.0
2     1.0
3     7.0
4    10.0
5     3.0
6     9.0
7     6.0
8     3.0
9     3.0
dtype: float64

In [280]:
#같은 점수를 실수로 표시 
#method사용의 기본값은 average : 같은점수를 평균내서 실수로 표시
obj1.rank(ascending=False,method='average')

0     8.0
1     5.0
2     1.0
3     7.0
4    10.0
5     3.0
6     9.0
7     6.0
8     3.0
9     3.0
dtype: float64

In [281]:
#method : 같은 값들중 가장 작은 값으로 랭크
obj1.rank(ascending=False,method='min')

0     8.0
1     5.0
2     1.0
3     7.0
4    10.0
5     2.0
6     9.0
7     6.0
8     2.0
9     2.0
dtype: float64

In [282]:
#max : 같은 값들중 가장 큰 값으로 랭크
obj1.rank(ascending=False,method='max')

0     8.0
1     5.0
2     1.0
3     7.0
4    10.0
5     4.0
6     9.0
7     6.0
8     4.0
9     4.0
dtype: float64

In [283]:
#first : 같은 값들중 인덱스번호가 적은순으로 랭크
obj1.rank(ascending=False,method='first')

0     8.0
1     5.0
2     1.0
3     7.0
4    10.0
5     2.0
6     9.0
7     6.0
8     3.0
9     4.0
dtype: float64

In [284]:

df =DataFrame({'영어':[60,80,70],'수학':[50,72,86]},
               index=['홍길동','박찬호','손흥민'])
df

영어  수학
홍길동  60  50
박찬호  80  72
손흥민  70  86

In [285]:
#과목별 학생순위
df.rank(ascending=False)

영어   수학
홍길동  3.0  3.0
박찬호  1.0  2.0
손흥민  2.0  1.0

In [286]:
#학생별 과목순위
df.rank(ascending=False,axis=1)

영어   수학
홍길동  1.0  2.0
박찬호  1.0  2.0
손흥민  2.0  1.0