In [ ]:
[문제106] 부서별 급여의 총액을 구하세요. 아래 결과 처럼 출력하세요.

10 4400.0
20 19000.0
30 24900.0
40 6500.0
50 156400.0
60 31584.6
70 10000.0
80 304500.0
90 82655.1
100 51608.0
110 20308.0
non 7000.0

In [51]:
import csv

file = open("c:\python\emp1.csv","r")
emp_csv = csv.reader(file)

emp_list = []
[emp_list.append(i) for i in emp_csv]

#dictionary key값으로 dep_id 를 모아서 sum
dep_dic = {}
for i in emp_list:
    if i[3] in (dep_dic.keys()):
        dep_dic[i[3]] = float(dep_dic[i[3]]) + float(i[5])
    else:
        dep_dic[i[3]] = float(i[5])

#list 형으로 바꿔주면서 ''값을 1000으로 바꿈
dep_list = []
for k,v in dep_dic.items():
    if k == '':
        dep_list.append(['1000',v])
    else:
        dep_list.append([k,v])

dep_sorted = sorted(dep_list, reverse=False, key=(lambda key: int(key[0])))

#출력은 1000으로 바뀐 ''값을 다시 non값으로 변경
for k,v in dep_sorted:
    if k == '1000':
        print('non',v)
    else:
        print(k,v)

100 155400.0
101 46116.8
102 9000.0
103 19800.0
108 40500.0
114 13900.0
120 22100.0
121 25400.0
122 23600.0
123 25900.0
124 23000.0
145 51000.0
146 51000.0
147 46600.0
148 51900.0
149 50000.0
201 6000.0
205 8300.0
non 24000.0


In [58]:
#선생님 풀이

import csv
import operator

file = open("c:\R\emp.csv",'r')
emp_csv = csv.reader(file)
dept_sum={}
for emp_list in emp_csv:
    if emp_list[10] in dept_sum:
        dept_sum[emp_list[10]] = float(dept_sum[emp_list[10]])+float(emp_list[7])
    else:
        dept_sum[emp_list[10]] = float(emp_list[7])
'''''''      
for k,v in sorted(dept_sum.items(),key=operator.itemgetter(0)):
    if k == '':
        print('non',v)
    else:
        print(k,v)
#부서 코드가 문자열이라 소트가 제대로 안됨
'''''''
#부서코드를 인트로 바꾸어주는 함수

def get_key(key):
    if key == '':
        return int(1000)
    else:
        return int(key)
#람다문 사용해서 key값을 집어넣음
for k,v in sorted(dept_sum.items(),key=lambda k:get_key(k[0])):
    if k == '':
        print('non',v)
    else:
        print(k,v)   

ValueError: could not convert string to float: 'SALARY'

In [57]:
#dic 형에서 sorted 가능하다..
def get_key(key):
    if key == '':
        return int(1000)
    else:
        return int(key)
x=sorted(dep_dic.items(),key=lambda k:get_key(k[0]))
x

[('100', 155400.0),
 ('101', 46116.8),
 ('102', 9000.0),
 ('103', 19800.0),
 ('108', 40500.0),
 ('114', 13900.0),
 ('120', 22100.0),
 ('121', 25400.0),
 ('122', 23600.0),
 ('123', 25900.0),
 ('124', 23000.0),
 ('145', 51000.0),
 ('146', 51000.0),
 ('147', 46600.0),
 ('148', 51900.0),
 ('149', 50000.0),
 ('201', 6000.0),
 ('205', 8300.0),
 ('', 24000.0)]

In [ ]:
[문제107] lst 변수에 2,6,1,8,7,9 가 입력 되어 있습니다. 
lst변수를 입력하면 최대값을 리턴 해주는 maxF함수를 생성하세요.

In [70]:
lst = [2,6,1,8,7,9]

def maxF(arg):
    x = 0
    for i in arg:
        if i > x:
            x = i
    return x

maxF(lst)

9

In [ ]:
[문제108] lst 변수에 2,6,1,8,7,9 가 입력 되어 있습니다. 
lst변수를 입력하면 최소값을 리턴 해주는  minF함수를 생성하세요.

In [72]:
lst = [2,6,1,8,7,9]

def minF(arg):
    x = arg[0]
    for i in arg:
        if i < x:
            x = i
    return x

minF(lst)

1

In [ ]:
*min, max 함수

In [73]:
min(lst)

1

In [74]:
max(lst)

9

In [ ]:
[문제109] 단어, 알파벳을 입력값으로 넣어서 단어 안에 알파벳 수를 출력하세요

<화면예>

wordF('happy','p')
2


In [83]:
x = 'happy accident'
y = 'p'
def coAlpha(arg1,arg2):
    x = 0
    for i in arg1:
        if i == arg2:
            x += 1
    return x

coAlpha(x,y)    

2

In [80]:
[문제110] 단어를 입력값으로 넣어서 알파벳을 출력하는데 중복되는 알파벳은 하나만 출력하세요.

True

In [ ]:
[문제110] 단어를 입력값으로 넣어서 알파벳을 출력하는데 중복되는 알파벳은 하나만 출력하세요.

alphaF('happy')
['h', 'a', 'p', 'y']

alphaF('intelligence')
['i', 'n', 't', 'e', 'l', 'g', 'c']


In [87]:
#그냥 set써서 풀어봄..
x = 'happy'

def setAlp(arg):
    return set(arg)

setAlp(x)

{'a', 'h', 'p', 'y'}

In [89]:
def alphaF(arg):
    freq = []
    for i in arg:
        if i not in freq:
            freq.append(i)
    return freq

alphaF(x)

['h', 'a', 'p', 'y']

In [ ]:
[문제111] 단어 철자의 빈도수를 출력하세요.


alphaF('intelligence')
{'i': 2, 'n': 2, 't': 1, 'e': 3, 'l': 2, 'g': 1, 'c': 1}

alphaF('happy')
{'h': 1, 'a': 1, 'p': 2, 'y': 1}


In [92]:
x = 'intelligence'
y = 'happy'

def alphaF(arg):
    freq = {}
    for i in arg:
        if i in freq.keys():
            freq[i] += 1
        else:
            freq[i] = 1
    return freq

print(alphaF(x))
print(alphaF(y))

{'i': 2, 'n': 2, 't': 1, 'e': 3, 'l': 2, 'g': 1, 'c': 1}
{'h': 1, 'a': 1, 'p': 2, 'y': 1}


In [ ]:
ㅁ pandas
- 데이터 분석기능을 제공하는 라이브러리
- 1차원배열 : Series
- 2차원배열 : DataFrame

#pandas.모듈명 대신 pd로 대체해서 사용
import pandas as pd
#Series,DataFrame 사용할때 아에 모듈안불러옴
from pandas import Series,DataFrame

# Series
- 1차원배열
- index(색인) 배열의 데이터에 연관된 이름을 가지고 있다.


In [93]:
import pandas as pd
from pandas import Series,DataFrame

In [96]:
s = Series([10,20,30,40])
s

0    10
1    20
2    30
3    40
dtype: int64

In [98]:
#색인 조회하기
s.index

RangeIndex(start=0, stop=4, step=1)

In [99]:
#값 조회하기
s.values

array([10, 20, 30, 40], dtype=int64)

In [ ]:
#색인 변경하기
		#R에서 rownames랑 비슷

In [100]:
s.index=['a','b','c','d']
s

a    10
b    20
c    30
d    40
dtype: int64

In [101]:
#인덱스와 값 가치 만들어주기
s2 = Series([10,20,30,40],index=['a','b','c','d'])
s2

a    10
b    20
c    30
d    40
dtype: int64

In [102]:
s2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [103]:
s2.values

array([10, 20, 30, 40], dtype=int64)

In [104]:
#색인 이름으로 value값 검색
s2['a']

10

In [ ]:
#여러개의 색인을 인수값으로 검색하려면 list형식으로 인수값을 넣어줘야된다.

In [105]:
s2[['a','b']]

a    10
b    20
dtype: int64

In [ ]:
#인덱스 번호로 value값 검색

In [106]:
s2[0]

10

In [108]:
s2[0:2]

a    10
b    20
dtype: int64

In [ ]:
#조건형으로 조회하기

In [109]:
s2[s2>20]

c    30
d    40
dtype: int64

In [ ]:
#색인이 존재하는지 확인

In [110]:
'a' in s2

True

In [111]:
'e' in s2

False

In [ ]:
#dictionary로 만든것을 Series로 변환

In [10]:
import pandas as pd
from pandas import Series,DataFrame

dict = {'a':10,'b':20,'c':30,'d':40}
s3 = Series(dic)
s3

a    10
b    20
c    30
d    40
dtype: int64

In [ ]:
#인덱스를 dictionary로 만들어주고 (s4) 
	s5 Series 만들때 index이름으로 사용하기

In [13]:
s4={'a','b','c','d'}
s5=Series(dict,index=s4)
s5

b    20
a    10
d    40
c    30
dtype: int64

In [14]:
#실제값이 없는 z라는 인덱스는 값이 NA 값으로 나옴
s4 = {'a','b','c','z'}
s5 = Series(dict,index=s4)
s5

b    20.0
a    10.0
z     NaN
c    30.0
dtype: float64

In [ ]:
z 인덱스 값을 찾을수 없기 때문에 NaN(Not a Nuber) 저장된다.
NaN 찾는 함수는 innull,notnull

In [16]:
pd.isnull(s5)

b    False
a    False
z     True
c    False
dtype: bool

In [17]:
pd.notnull(s5)

b     True
a     True
z    False
c     True
dtype: bool

In [19]:
dict = {"서울":3000,"부산":2000,"인천":1000,"제주":500}
s6 = Series(dict)
s6

서울    3000
부산    2000
인천    1000
제주     500
dtype: int64

In [21]:
city = {'서울','대구','인천','제주'}
s7 = Series(dict,index=city)
s7

인천    1000.0
제주     500.0
서울    3000.0
대구       NaN
dtype: float64

In [26]:
#index 값 바꾸기
s7.index=["서울","부산","인천","제주"]

In [25]:
s7

서울    1000.0
부산     500.0
인천    3000.0
제주       NaN
dtype: float64

In [33]:
Series({'a':[10,20],"b":20})

a    [10, 20]
b          20
dtype: object

In [ ]:
# DataFrame
- 2차원 배열
- 표같은 스프레드시트 형식의 자료구조
- 각컬럼은 서로 다른 종류의 값(숫자,문자,불리언)
- R 언어의 data.frame

In [30]:
df1 = DataFrame([[1,2,3],[4,5,6],[7,8,9]])
df1

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [34]:
df2 = DataFrame({'도시':["서울","광주","부산","인천"],"인구수":[2000,1000,1500,500]})
df2

도시   인구수
0  서울  2000
1  광주  1000
2  부산  1500
3  인천   500

In [53]:
#columns 와 index 지정해서 DataFrame 만들기
df2.values

array([['서울', 2000],
       ['광주', 1000],
       ['부산', 1500],
       ['인천', 500]], dtype=object)

In [46]:
df3 =DataFrame(df2.values,columns=['도시','인구수'],index=['one','two','three','four'])
df3

도시   인구수
one    서울  2000
two    광주  1000
three  부산  1500
four   인천   500

In [47]:
#도시 이름만 확인
df3.도시

one      서울
two      광주
three    부산
four     인천
Name: 도시, dtype: object

In [50]:
df3['도시']

one      서울
two      광주
three    부산
four     인천
Name: 도시, dtype: object

In [51]:
df3[['도시','인구수']]

도시   인구수
one    서울  2000
two    광주  1000
three  부산  1500
four   인천   500

In [52]:
#연산도 가능함
df3['인구수']*10

one      20000
two      10000
three    15000
four      5000
Name: 인구수, dtype: object

In [54]:
#실제 변수에 변화는 없음
df3

도시   인구수
one    서울  2000
two    광주  1000
three  부산  1500
four   인천   500

In [55]:
df3.columns

Index(['도시', '인구수'], dtype='object')

In [56]:
df3.index

Index(['one', 'two', 'three', 'four'], dtype='object')

In [57]:
df3.values

array([['서울', 2000],
       ['광주', 1000],
       ['부산', 1500],
       ['인천', 500]], dtype=object)

In [67]:
#index번호로 indexing
df3.iloc[0]

도시       서울
인구수    2000
Name: one, dtype: object

In [72]:
#index 이름으로 indexing
df3.loc['one']

도시       서울
인구수    2000
Name: one, dtype: object

In [71]:
df3.loc[['one','two']]

도시   인구수
one  서울  2000
two  광주  1000

In [ ]:
#series를 data프레임에 합치기

In [73]:
v = Series([1000,2000,3000,4000],index=['one','two','three','four'])
v

one      1000
two      2000
three    3000
four     4000
dtype: int64

In [88]:
df3['부채'] = v
df3

도시 인구수    부채
one    2000  서울  1000
two    1000  광주  2000
three  1500  부산  3000
four    500  인천  4000

In [89]:
# 색인을 기준으로 데이터 뒤바꾸기
df3[['도시','인구수']] = df3[['인구수','도시']]
df3

도시   인구수    부채
one    서울  2000  1000
two    광주  1000  2000
three  부산  1500  3000
four   인천   500  4000

In [90]:
#색인 삭제하기
del df3['부채']
df3

도시   인구수
one    서울  2000
two    광주  1000
three  부산  1500
four   인천   500

In [92]:
#dic 타입의 데이터로 DataFrame 만들기
data={'서울':{2001:200,2002:300},'부산':{2000:10,2001:20,2002:30}}
data

{'서울': {2001: 200, 2002: 300}, '부산': {2000: 10, 2001: 20, 2002: 30}}

In [101]:
df4 = DataFrame(data)   #서울은 2000 의 값이 없어서 NaN으로 나옴
df4

서울  부산
2000    NaN  10
2001  200.0  20
2002  300.0  30

In [ ]:
reindex(재색인) : 새로운 색인에 맞도록 객체를 새로 생성하는 기능

In [98]:
obj2 = df4.reindex(['a','b','c','d'])
obj2

서울  부산
a NaN NaN
b NaN NaN
c NaN NaN
d NaN NaN

In [100]:
obj3 = df4.reindex(['a','b','c','d','f'])
obj3

서울  부산
a NaN NaN
b NaN NaN
c NaN NaN
d NaN NaN
f NaN NaN

In [105]:
obj4 = df4.reindex(['a','b','c','d','f'],fill_value=0)
obj4

서울  부산
a  0.0   0
b  0.0   0
c  0.0   0
d  0.0   0
f  0.0   0

In [ ]:
#numpy를 이용해 array타입의 데이터를 DataFrame에 넣어보자

In [106]:
import numpy as np

In [107]:
np.arange(4)

array([0, 1, 2, 3])

In [108]:
df = DataFrame(np.arange(9))
df

0
0  0
1  1
2  2
3  3
4  4
5  5
6  6
7  7
8  8

In [ ]:
#arrange사용해서 3행 3열의 array만들기

In [113]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [115]:
#컬럼명 지정해서 DataFrame에 넣어보자
df = DataFrame(np.arange(9).reshape(3,3),index=["a","b","c"],columns=['x','y','z'])
df

x  y  z
a  0  1  2
b  3  4  5
c  6  7  8

In [117]:
#d라는 행을 추가하면 값이 없어서 NaN 으로 입력됨
df.reindex(["a","b","c","d"])

x    y    z
a  0.0  1.0  2.0
b  3.0  4.0  5.0
c  6.0  7.0  8.0
d  NaN  NaN  NaN

In [ ]:
#행추가하면서 값은 한줄위의 값으로 채워넣기 : method='ffill' or method='pad'

In [118]:
df.reindex(["a","b","c","d"],method='ffill')

x  y  z
a  0  1  2
b  3  4  5
c  6  7  8
d  6  7  8

In [119]:
df.reindex(["a","b","c","d"],method='pad')

x  y  z
a  0  1  2
b  3  4  5
c  6  7  8
d  6  7  8

In [120]:
#column 명도 바꿔보자
df.reindex(columns=['y','x','z'])

y  x  z
a  1  0  2
b  4  3  5
c  7  6  8

In [121]:
# 0,2,4 index를 갖는 Series를 만들고 reindex 해보자
obj = Series(['blue','red','yellow'],index=[0,2,4])
obj

0      blue
2       red
4    yellow
dtype: object

In [122]:
obj2 = obj.reindex(range(6))
obj2

0      blue
1       NaN
2       red
3       NaN
4    yellow
5       NaN
dtype: object

In [123]:
obj2 = obj.reindex(range(6),method = 'ffill') #앞의 값으로 채운다. (front fill)
obj2

0      blue
1      blue
2       red
3       red
4    yellow
5    yellow
dtype: object

In [124]:
obj2 = obj.reindex(range(6), method='pad') #앞의 값으로 채운다.
obj2

0      blue
1      blue
2       red
3       red
4    yellow
5    yellow
dtype: object

In [135]:
obj2 = obj.reindex(range(6),fill_value = 'white') # white으로 채운다.
obj2

0      blue
1     white
2       red
3     white
4    yellow
5     white
dtype: object

In [136]:
#5번 인덱스의 값만 바꾼다...
obj2[5]='blue'
obj2

0      blue
1     white
2       red
3     white
4    yellow
5      blue
dtype: object

In [139]:
#series 하나 만들고..행삭제를 해보자..
obj = Series(np.arange(5),index=['a','b','c','d','e'])
obj = obj.drop('e')
obj

a    0
b    1
c    2
d    3
dtype: int32

In [140]:
# a,b 행도 삭제
obj = obj.drop(['a','b'])
obj

c    2
d    3
dtype: int32

In [ ]:
#DataFrame의 행,열삭제

In [151]:
df = DataFrame(np.arange(16).reshape(4,4),
               index = ['w','x','y','z'],
              columns = ['one','two','three','four'])
df

one  two  three  four
w    0    1      2     3
x    4    5      6     7
y    8    9     10    11
z   12   13     14    15

In [152]:
#행을 (2개) 삭제

df = df.drop(['w','x'],axis = 0)
df

one  two  three  four
y    8    9     10    11
z   12   13     14    15

In [145]:
#열을(1개행) 삭제

df = df.drop('one',axis=1)
df

two  three  four
y    9     10    11
z   13     14    15

In [153]:
# column 삭제는 del df['부채'] 로도 가능
# 바로 변수에 적용되니 drop을 사용하자
del df['one']
df

two  three  four
y    9     10    11
z   13     14    15

In [ ]:
# 슬라이싱 해보기

In [ ]:
    # Seires 슬라이싱

In [154]:
obj = Series([10,20,30,40],index=['a','b','c','d'])
obj

a    10
b    20
c    30
d    40
dtype: int64

In [155]:
obj['a']

10

In [156]:
obj[0]

10

In [158]:
obj[1:3]

b    20
c    30
dtype: int64

In [ ]:
#이름을 가지고 슬라이싱하기
	#b,c색인으로 슬라이싱

In [159]:
obj['b':'c']

b    20
c    30
dtype: int64

In [ ]:
#리스트형으로 a,c 색인 집어넣어 a랑 c색인만 보기

In [162]:
obj[['a','c']]

a    10
c    30
dtype: int64

In [ ]:
#조건부로 슬라이싱

In [164]:
obj[obj<30]

a    10
b    20
dtype: int64

In [ ]:
    # DataFrame 슬라이싱

In [165]:
df = DataFrame(np.arange(16).reshape(4,4),
               index=['w','x','y','z'],
               columns=['one','two','three','four'])
df

one  two  three  four
w    0    1      2     3
x    4    5      6     7
y    8    9     10    11
z   12   13     14    15

In [ ]:
#열을 기준으로 해당열을 조회

In [167]:
df['one']

w     0
x     4
y     8
z    12
Name: one, dtype: int32

In [187]:
df[['one','two']]

one  two
w    0    1
x    4    5
y    8    9
z   12   13

In [ ]:
#행을 기준으로 해당 행을 조회

In [188]:
df[2:]

one  two  three  four
y    8    9     10    11
z   12   13     14    15

In [190]:
df[0:1]

one  two  three  four
w    0    1      2     3

In [192]:
df.iloc[0]    # Series type 으로 나온다

one      0
two      1
three    2
four     3
Name: w, dtype: int32

In [196]:
df.loc['w']    # Series type 으로 나온다

one      0
two      1
three    2
four     3
Name: w, dtype: int32

In [ ]:
#boolen 형식으로 보기

In [199]:
df < 5

one    two  three   four
w   True   True   True   True
x   True  False  False  False
y  False  False  False  False
z  False  False  False  False

In [ ]:
# 행과열의 교차점만 확인하기

#x와 one의 교차점 확인

In [202]:
df.loc['x','one']

4

In [204]:
df.loc['x':,'two':]

two  three  four
x    5      6     7
y    9     10    11
z   13     14    15

In [208]:
df.loc['x':,'two']

x     5
y     9
z    13
Name: two, dtype: int32